#
# Alacritty config
#

env:
  TERM: xterm-256color


shell:
    program: /usr/bin/zsh
    args:
      - -l
      - -c
      # - "tmux attach || tmux -f ~/.config/tmux/tmux.conf"
      - "tmux attach || ~/setup/tools/devmux || tmux -f ~/.config/tmux/tmux.conf || tmux"


window:
  dimensions:
    columns: 200
    lines: 57

  padding:
    x: 5
    y: 5

  dynamic_padding: true
  startup_mode: Windowed

scrolling:
  history: 10000
  multiplier: 3
  scrolling_multiplier: 3

tabspaces: 4

draw_bold_text_with_bright_colors: true

visual_bell:
  animation: EaseOutExpo
  duration: 0
  color: '0xffffff'

# Colors (Hyper)
colors:
  # Default colors
  primary:
    background: '0x000000'
    foreground: '0xffffff'
  cursor:
    text: '0xF81CE5'
    cursor: '0xffffff'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xfe0100'
    green:   '0x33ff00'
    yellow:  '0xfeff00'
    blue:    '0x0066ff'
    magenta: '0xcc00ff'
    cyan:    '0x00ffff'
    white:   '0xd0d0d0'

  # Bright colors
  bright:
    black:   '0x808080'
    red:     '0xfe0100'
    green:   '0x33ff00'
    yellow:  '0xfeff00'
    blue:    '0x0066ff'
    magenta: '0xcc00ff'
    cyan:    '0x00ffff'
    white:   '0xFFFFFF'

background_opacity: 0.80

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  hide_when_typing: true


selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"
  save_to_clipboard: true

dynamic_title: true

cursor:
  style: Block
  unfocused_hollow: true

live_config_reload: true
enable_experimental_conpty_backend: false

alt_send_esc: true

debug:
  render_timer: false
  persistent_logging: false
  log_level: Warn
  print_events: false
  ref_test: false

