#!/bin/sh
# Xfce is defualt
session=${1:-xfce}

# very brittle and will probably break if 2 monitors
MONITOR=$(xrandr --listactivemonitors | awk '{ print $4 }')
MODE="1920x1080"

if grep 'hypervisor' /proc/cpuinfo; then
    xrandr --output Virtual1 --mode "$MODE"
else
    # xrandr --output "HDMI-0" --mode "$MODE" --output "DP-0" --mode "$MODE" &
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto
fi

xbindkeys -p &

case $session in
    xfce|xfce4  ) exec startxfce4;;
    # no known session, try to run as command
    *           ) exec $1;;
esac
